# -- Numbers -------------------------------------------------------------------

- 0â‚€â°
- 1â‚Â¹
- 2â‚‚Â²
- 3â‚ƒÂ³
- 4â‚„â´
- 5â‚…âµ
- 6â‚†â¶
- 7â‚‡â·
- 8â‚ˆâ¸
- 9â‚‰â¹

# -- Small Letters -------------------------------------------------------------

# Alpha, Subscript Alpha, Alien Monster
- aÎ±â‚ğŸ‘¾
# Beta, Subscript Beta
- bÎ²áµ¦
# Chi, Subscript Chi, Copyright, Cyclone, Video Camera, Clapper Board
- cÏ‡áµªÂ©ğŸ“¹ğŸŒ€
# Delta
- dÎ´
# Epsilon, Eta, Subscript E, Element Of, Not An Element Of
- eÎµÎ·â‚‘âˆˆâˆ‰
# Gamma, Subscript Gamma, Grinning Face
- gÎ³áµ§ğŸ˜€
# Heavy Black Heart
- hâ¤ï¸
# Iota, Subscript I, Superscript I
- iÎ¹áµ¢â±
# Kappa
- kÎº
# Lambda
- lÎ»
# Mu, Musical Note, Microphone
- mÎ¼ğŸµğŸ™
# Nu, Superscript N
- nÎ½â¿
# Omega, White Bullet, Subscript O
- oÏ‰â—¦â‚’
# Pi, Phi, Subscript Phi, Psi, Personal Computer, Pile Of Poo
- pÏ€Ï†áµ©ÏˆğŸ’»ğŸ’©
# Rho, Subscript Rho, Subscript R
- rÏáµ¨áµ£
# Sigma, Sigma (Alternative Form), Sparkles, Sunflower
- sÏƒÏ‚âœ¨ğŸŒ»
# Theta, Tau, Television
- tÎ¸Ï„ğŸ“º
# Upsilon, Subscript U, Union, Unicorn Face
- uÏ…áµ¤âˆªğŸ¦„
# Subscript V, Or, Down Arrow, Checkmark
- váµ¥âˆ¨â†“âœ“
# Xi, Subscript X
- xÎ¾â‚“
# Zeta
- zÎ¶

# -- Capital Letters -----------------------------------------------------------

- AÎ‘    # Alpha
- BÎ’    # Beta
- CÎ§    # Chi
- DÎ”    # Delta
- EÎ•Î—âˆƒâˆ„ # Epsilon, Eta, Exists, Exists Not
- GÎ“    # Gamma
- IÎ™    # Iota
- KÎš    # Kappa
- LÎ›    # Lambda
- MÎœ    # Mu
- NÎâ„•   # Nu, Double Struck Capital N
- OÎ©âˆ…   # Omega, Empty Set
- PÎ Î¦Î¨  # Pi, Phi, Psi
- RÎ¡    # Rho
- SÎ£    # Sigma
- TÎ˜Î¤   # Theta, Tau
- UÎ¥    # Upsilon
- Vâˆ€    # For All
- XÎ    # Xi
- ZÎ–â„¤   # Zeta, Double Struck Capital Z

# -- Misc ----------------------------------------------------------------------

- ^âˆ§Â¬â†‘â‡‘
- <â†â‡
- '>â†’â‡’'
- =â‚Œâ¼â†”ï¸â‡”â‰”â‰•
- -â‚‹â»
- +â‚Šâº
- (â‚â½âŠ‚âŠ†âŠŠ
- )â‚â¾âŠƒâŠ‡âŠ‹
- '[âŠâŸ¦âŒŠ'
- ']âŠâŸ§âŒ‹'
- $â‡§âŒ¥âŒ˜â†©â‹â‡¥âŒ« # Key Symbols
